export const dataNavigate = [
  {
    category: "THIẾT BỊ PHÒNG THÍ NGHIỆM",
    datas: [
      {
        subcategory: "Máy quang phổ",
      },
      {
        subcategory: "Máy đo chỉ tiêu nước cầm tay - để bàn",
      },
      {
        subcategory: "Máy đo độ ồn",
      },
      {
        subcategory: "Máy lấy mẫu khí",
      },
      {
        subcategory: "Máy đo khí Môi trường",
      },
      {
        subcategory: "Nồi hấp tiệt trùng",
      },
      {
        subcategory: "Máy cất nước",
      },
      {
        subcategory: "Máy khuấy Jartest",
      },
      {
        subcategory: "Máy ly tâm",
      },
      {
        subcategory: "Tủ Ấm - Tủ Sấy",
      },
      {
        subcategory: "Lò Nung",
      },
      {
        subcategory: "Bể điều nhiệt",
      },
      {
        subcategory: "Tủ An toàn Sinh Học - Tủ hút",
      },
      {
        subcategory: "Kính hiển vi",
      },
      {
        subcategory: "Bộ Phân tích BOD",
      },
      {
        subcategory: "Thiết bị chưng cất đạm",
      },
    ],
  },
  {
    category: "CÂN ĐIỆN TỬ",
    datas: [
      {
        subcategory: "Cân phân tích ẩm",
      },
      {
        subcategory: "Cân Phân tích",
      },
      {
        subcategory: "Cân kỹ Thuật",
      },
    ],
  },
  {
    category: "MÁY ĐO ĐỘ ẨM",
    datas: [
      {
        subcategory: "Máy đo độ ẩm ngũ cốc",
      },
      {
        subcategory: "Máy đo độ ẩm gỗ",
      },
      {
        subcategory: "Máy đo độ ẩm mùn cưa",
      },
      {
        subcategory: "Máy đo độ ẩm giấy",
      },
    ],
  },
  {
    category: "DỤNG CỤ - HÓA CHẤT - VẬT TƯ TIÊU",
    datas: [
      {
        subcategory: "Dụng cụ thủy tinh - Duran",
      },
      {
        subcategory: "Dụng Cụ Thủy Tinh Isolab",
      },
      {
        subcategory: "Micropipette",
      },
      {
        subcategory: "Dụng cụ thủy tinh Onelab",
      },
      {
        subcategory: "Giấy Lọc Whatman - Advantec",
      },
      {
        subcategory: "Syringe lọc cho Sắc ký HPLC",
      },
      {
        subcategory: "Hóa chất tinh khiết Merck - Sigma",
      },
      {
        subcategory: "Hóa chất tinh khiết Fisher",
      },
      {
        subcategory: "Môi trường vi sinh Himedia",
      },
      {
        subcategory: "Chất chuẩn ERA - NSI",
      },
    ],
  },
  {
    category: "DỊCH VỤ SỬA CHỮA THIẾT BỊ",
    datas: [
      {
        subcategory: "Sửa chữa 1",
      },
      {
        subcategory: "Sửa chữa 2",
      },
      {
        subcategory: "Sửa chữa 3",
      },
      {
        subcategory: "Sửa chữa 4",
      },
    ],
  },
];

export const productData = [
  {
    category: "THIẾT BỊ PHÒNG THÍ NGHIỆM",
    subcategories: [
      {
        name: "Máy khuấy Jartest",
        items: [
          {
            id: 1,
            image: "/work/Máy khuấy Jartest.jpg",
            name: "Máy khuấy Jartest loại xách tay đi hiện trường",
            description:
              "Hãng sản xuất: Velp - Ý. Model: FP4. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính FP4, 04 cánh khuấy, Sách hướng dẫn sử dụng.",
          },

          {
            id: 2,
            image: "/work/Máy khuấy Jartest.jpg",
            name: "Máy khuấy Jartest(4 vị trí điện tử hiện số)",
            description:
              "Hãng sản xuất: Velp - Ý. Model: JLT4. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính JLT4, 04 cánh khuấy, Sách hướng dẫn sử dụng.",
          },
          {
            id: 3,
            image: "/work/Máy khuấy Jartest.jpg",
            name: "Máy khuấy Jartest(4 vị trí độc lập)",
            description:
              "Hãng sản xuất: Velp - Ý. Model: FC4S. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính FC4S, 04 cánh khuấy, Sách hướng dẫn sử dụng.",
          },
          {
            id: 4,
            image: "/work/Máy khuấy Jartest.jpg",
            name: "Máy khuấy Jartest(6 vị trí điện tử hiện số)",
            description:
              "Hãng sản xuất: Velp - Ý. Model: JLT6. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính, 06 cánh khuấy, Sách hướng dẫn sử dụng.",
          },
          {
            id: 5,
            image: "/work/Máy khuấy Jartest.jpg",
            name: "Máy khuấy Jartest(6 vị trí độc lập)",
            description:
              "Hãng sản xuất: Velp - Ý. Model: FC6S. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính FC6S, 06 cánh khuấy, Sách hướng dẫn sử dụng.",
          },
        ],
      },
      {
        name: "Máy ly tâm",
        items: [
          {
            id: 1,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm đa năng tốc độ tối đa 14,000 v/phút",
            description:
              "Hãng sản xuất: Hermle - Đức. Model: Z307. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính Z307, Dây nguồn, Sách hướng dẫn sử dụng.",
          },
          {
            id: 2,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm để bàn (6000v/phút) - Model Z 206A",
            description:
              "Hãng sản xuất: Hermle - Đức. Cung cấp bao gồm: Máy chính Z206A, 01 roto góc 12x 15ml mã 221.54 V01, Sách hướng dẫn sử dụng.",
          },
          {
            id: 3,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm để bàn (6000v/phút) - Model Z 207A",
            description:
              "Hãng sản xuất: Hermle - Đức. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính Z207A, Roto góc 8x15ml hoặc 4x50ml, Sách hướng dẫn sử dụng.",
          },
          {
            id: 4,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm để bàn (6000v/phút)",
            description:
              "Đo độ hấp thụ và truyền qua của các mẫu chất lỏng ở dải sóng UV-Vis.",
          },
          {
            id: 5,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm đa năng tốc độ tối đa 14,000 v/phút",
            description:
              "Đo độ hấp thụ và truyền qua của các mẫu chất lỏng ở dải sóng UV-Vis.",
          },
          {
            id: 6,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description:
              "Hãng sản xuất: Hermle – Đức. Model: Z216 MK. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính model Z-216 MK (Code: 305.00 V05), Roto góc loại 24 vị trí dùng cho ống 1.5/2.0ml có nắp đậy (Code: 220.87 V14), Dây nguồn và sách hướng dẫn sử dụng.",
          },
          {
            id: 7,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description:
              "Hãng sản xuất: Hermle – Đức. Model: Z216 MK. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính model Z-216 MK (Code: 305.00 V05) chưa bao gồm roto, các loại roto khách hàng lựa chọn bên dưới, Dây nguồn và sách hướng dẫn sử dụng.",
          },
          {
            id: 8,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description:
              "Model: Z207MK. Hãng sản xuất: Hermle - Đức. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính Z207MK, Roto góc 18x1.5/2ml, Sách hướng dẫn sử dụng.",
          },
          {
            id: 9,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm thường (ly tâm ống PCR)",
            description:
              "Hãng sản xuất: Hermle - Đức. Model: Z 216M. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính model Z 216 M, Roto góc loại 24 vị trí dùng cho ống 1.5/2.0ml có nắp đậy (Code: 220.87 V14), Dây nguồn và sách hướng dẫn sử dụng.",
          },
          {
            id: 10,
            image: "/work/Máy ly tâm.jpeg",
            name: "Máy ly tâm ống Microlitre (ống PCR)",
            description:
              "Model: Z207M. Hãng sản xuất: Hermle - Đức. Xuất xứ: Đức. Cung cấp bao gồm: Máy chính Z207M, Roto góc 24x1.5/2ml, Sách hướng dẫn sử dụng.",
          },
        ],
      },
      {
        name: "Kính hiển vi",
        items: [
          {
            id: 1,
            image: "/work/Kính hiển vi.png",
            name: "Kính hiển vi 3 mắt",
            description:
              "Hãng sản xuất: Optika - Ý. Model: B-193PL. Xuất xứ: Ý. Cung cấp bao gồm: Máy chính, Túi phủ chống bụi, Dầu soi 10ml, Hướng dẫn sử dụng (bản tải trên website).",
          },
          {
            id: 2,
            image: "/work/Kính hiển vi.png",
            name: "Kính hiển vi 3 mắt (Kết nối với camera)",
            description:
              "Hãng sản xuất: Optika – Ý. Model: B-293. Xuất xứ: Ý. Cung cấp bao gồm: Thân kính, Thị kính (mắt): 02 chiếc 10x/20mm, Bộ thị kính: N-PLAN 4x/0.10, N-PLAN 10x/0.25, N-PLAN 40x/0.65, N-PLAN 100x/1.25 (Oil/Water), Bàn xa kẹp mẫu: 1 chiếc, Bóng đèn X-LED: 1 chiếc, Mâm lắp vật kính: 1 chiếc loại 4 vị trí, Đầu lắp thị kính: 1 bộ, Túi che kính: 1 chiếc, Lọ dầu soi: 1 lọ, Sách hướng dẫn sử dụng.",
          },
          {
            id: 3,
            image: "/work/Kính hiển vi.png",
            name: "Kính hiển vi sinh học 3 mắt (Kính kết nối với camera)",
            description:
              "Model: B-293Pli. Hãng sản xuất: Optika- Ý. Xuất xứ: Ý. Cấu hình cung cấp: Thân kính: 1 chiếc, Thị kính (mắt): 02 chiếc 10x/20mm, IOS 4X, N.A. 0,10, W.D. 18 mm, IOS 10X, N.A. 0,25, W.D. 7 mm, IOS 40X, N.A. 0,65, W.D. 0,53 mm, IOS 100X, N.A. 1,25, W.D. 0,13 mm (sử dụng dầu soi), Bàn xa kẹp mẫu: 1 chiếc, Bóng đèn X-LED: 1 chiếc, Mâm lắp vật kính: 1 chiếc loại 4 vị trí, Đầu lắp thị kính: 1 bộ, Túi che kính: 1 chiếc, Lọ dầu soi: 1 lọ, Sách hướng dẫn sử dụng.",
          },
          {
            id: 4,
            image: "/work/Kính hiển vi.png",
            name: "Camera cho kính hiển vi",
            description:
              "Hãng sản xuất: Optika – Ý. Model: C-B1. Xuất xứ: Ý. Cung cấp bao gồm: Cáp USB 1.8m, Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm, Tiêu bản chuẩn, C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli, Phần mềm kết nối với máy tính download trực tiếp trên website.",
          },
          {
            id: 5,
            image: "/work/Kính hiển vi.png",
            name: "Bộ Camera",
            description:
              "Model: C-B5. Hãng sản xuất: Optika – Ý. Xuất xứ: Ý. Cung cấp bao gồm: Cáp USB 1.8m, Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm, Tiêu bản chuẩn, C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli, Phần mềm kết nối với máy tính download trực tiếp trên website.",
          },
          {
            id: 6,
            image: "/work/Kính hiển vi.png",
            name: "Bộ Camera",
            description:
              "Model: C-B10+. Hãng sản xuất: Optika – Ý. Xuất xứ: Ý. Cung cấp bao gồm: Cáp USB 1.8m, Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm, Tiêu bản chuẩn, C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli, Phần mềm kết nối với máy tính download trực tiếp trên website.",
          },
        ],
      },
    ],
  },
];
export const productDataID = [
  {
    category: "THIẾT BỊ PHÒNG THÍ NGHIỆM",
    subcategories: [
      {
        name: "Máy khuấy Jartest",
        items: [
          {
            id: 1,
            images: ["/work/1.png", "/work/2.png"],
            name: "Máy khuấy Jartest (leaching test/Jar-Test) loại xách tay đi hiện trường",
            description: [
              "Máy khuấy Jartest (leaching test/Jar-Test) loại xách tay đi hiện trường",
              "Hãng sản xuất: Velp - Ý",
              "Model: FP4",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Máy chính FP4 + 04 cánh khuấy+ Sách hướng dẫn sử dụng",
            ],

            price: 5000000,
            body: [
              {
                name: "THÔNG TIN",
                description: [
                  "Model FP4 máy Jartest 4 vị trí có thể sách đi hiện trường, với bộ điều khiển dạng cơ.",
                  "Kết quả đáng tin cậy và lặp lại.",
                  "Động cơ khuấy DC điều khiển điện tử với tốc độ chính xác.",
                  "Được thiết kế nhỏ gọn có thể sách đi hiện trường và kiểm tra mẫu tức thì.",
                  "Máy có thể sử dụng pin chuyên dụng hoặc xạc pin từ ôtô.",
                  "4 mẫu chạy đồng thời.",
                  "Đèn chiếu sáng đặt ở giữa dễ quan sát khi vận hành.",
                  "Cánh khuấy có thể điều chỉnh độ cao bằng tay.",
                  "Số vị trí khuấy: 4 bố trí theo hình vuông tiết kiệm diện tích.",
                  "Kết cấu được làm bằng thép sơn tĩnh điện phủ lớp sơn Epoxy chịu ăn mòn hoá chất và các tác nhân cơ học thông thường.",
                  "Cánh khuấy và trục khuấy làm bằng thép không gỉ có thể điều chỉnh được độ cao.",
                  "Động cơ điều khiển DC.",
                  "Tốc độ quay có thể cài đặt theo các mức 20-40-50-100-200 v/phút.",
                  "Thời gian có thể cài đặt từ 0-30 phút dạng analog hoặc chạy liên tục.",
                  "Nguồn điện sử dụng: 100 - 240 V / 50-60 Hz.",
                  "Trọng lượng máy: 4.8kg.",
                  "Công suất: 6W.",
                  "Kích thước WxHxD: 250x320x250 mm.",
                  "Các phụ kiện lựa chọn thêm: Cốc thủy tinh loại 1000ml, Glass beaker 1000 ml, Phễu đong định mức bằng thủy tinh, Glass graduated imhoff cone, Giá giữ bằng gỗ phễu đong loại 2 vị trí, Stand for two imhoff cones.",
                ],
              },
              {
                name: "ĐIỀU KIỆN THƯƠNG MẠI:",
                description: [
                  "1. Giá trên là giá đã bao gồm thuế GTGT.",
                  "2. Thời gian giao hàng: 1-2 ngày đối với hàng có sẵn, và 6 ~ 8 tuần đối với hàng phải đặt, kể từ ngày bên bán nhận được tiền đặt cọc của bên mua.",
                  "3. Chất lượng: hàng mới 100%, nguyên đai kiện, sản xuất năm 2022 -2023.",
                  "4. Địa điểm giao hàng: Phòng thí nghiệm bên mua.",
                  "5. Thanh toán:",
                  "- Bằng chuyển khoản, séc theo tỷ giá bán ra của Ngân hàng Ngoại Thương tại thời điểm thanh toán (nếu là ngoại tệ).",
                  ,
                  "- Thanh toán:",
                  "+ 1 lần:",
                  "  • Thanh toán 100% tổng giá trị hợp đồng trước khi giao hàng đối với hàng có sẵn.",
                  "+ 2 lần:",
                  "  • Lần 1: Thanh toán 50% tổng giá trị hợp đồng trong vòng 07 ngày ngay sau khi ký kết hợp đồng.",
                  "  • Lần 2: Thanh toán 50% tổng giá trị hợp đồng trong vòng 03 ngày kể từ ngày thông báo giao hàng và bên mua kiểm tra hàng hóa.",
                  "- Đơn vị thụ hưởng: Công ty TNHH Thiết bị Khoa học & Công nghệ Kim Ngân.",
                  "  • Số tài khoản: 186704072464536.",
                  "  • Tại: Ngân hàng TMCP phát triển TP Hồ Chí Minh, Chi nhánh Hùng Vương, Hà Nội.",
                  "6. Bảo hành 12 tháng kể từ ngày xuất kho đối với máy chính, không bảo hành phần tiêu hao và dễ vỡ.",
                  "7. Bảng báo giá có hiệu lực hết 31 tháng 12 năm 2023.",
                  "KIMTECO., LTD",
                  "Lưu Trường Thọ",
                  "Giám đốc",
                  "Mobile: 0904165623",
                  "Email: kimteco@kimteco.vn",
                ],
              },
            ],
          },
          {
            id: 2,
            images: ["/work/1.png"],
            name: "Máy khuấy Jartest (leaching test/Jar-Test) (4 vị trí điện tử hiện số)",
            description: [
              "Máy khuấy Jartest (leaching test/Jar-Test) (4 vị trí điện tử hiện số)",
              "Hãng sản xuất: Velp - Ý",
              "Model: JLT4 Xuất xứ: Ý ",
              "Cung cấp bao gồm: + Máy chính JLT4 + 04 cánh khuấy + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "THÔNG TIN",
                description: [
                  "Model JLT4 được điều khiển bằng bộ vi xử lý với thiết kế đơn giản, dễ sử dụng. Bảng điều khiển phía trước dễ dàng cài đặt và quan sát các thông số cài đặt.",
                  "Cài đặt tốc độ quay từ 10 đến 300 vòng/ phút với độ phân giải là 1 vòng/ phút.",
                  "Thời gian khuấy được cài đặt trước và hiển thị thời gian hoạt động còn lại dưới dạng giờ hoặc phút.",
                  "Máy kiểm tra Jar-Test loại điện tử hiện số dùng để kiểm tra hàm lượng phèn trong nước, chọn các loại hoá chất của các chất làm đông với mục đích để di chuyển của các thành phần lơ lửng trong nước và sự ô nhiễm được xác định từ kết quả kiểm tra tại phòng thí nghiệm được gọi là phương pháp Jar-Test. Máy cũng ứng dụng kiểm tra các kim loại nặng trong nước thải bằng cách hoà tan bằng axit acetic hoặc CO2 bão hoà trong nước trước khi thải ra môi trường.",
                  "Số vị trí khuấy: 4 đồng thời.",
                  "Kết cấu được làm bằng thép sơn tĩnh điện phủ lớp sơn Epoxy chịu ăn mòn hoá chất và các tác nhân cơ học thông thường.",
                  "Cánh khuấy và trục khuấy làm bằng thép không gỉ có thể điều chỉnh được độ cao.",
                  "Động cơ điều khiển DC.",
                  "Tốc độ khuấy 10 - 300 vòng/phút, độ phân giải 1 vòng/phút.",
                  "Thời gian được điều khiển bằng bộ vi xử lý có 2 khoảng: 0-999 phút hoặc 0-99 giờ.",
                  "Nguồn điện sử dụng: 220V/50Hz.",
                  "Trọng lượng máy: 13kg.",
                  "Công suất: 11W.",
                  "Kích thước WxHxD: 645 x 347 x 260 mm.",
                  "Các phụ kiện lựa chọn thêm: Cốc thủy tinh loại 1000ml, Glass beaker 1000 ml, Phễu đong định mức bằng thủy tinh, Glass graduated imhoff cone, Giá giữ bằng gỗ phễu đong loại 2 vị trí, Stand for two imhoff cones.",
                ],
              },
              {
                name: "ĐIỀU KIỆN THƯƠNG MẠI:",
                description: [
                  "1. Giá trên là giá đã bao gồm thuế GTGT.",
                  "2. Thời gian giao hàng: 1-2 ngày đối với hàng có sẵn, và 6 ~ 8 tuần đối với hàng phải đặt, kể từ ngày bên bán nhận được tiền đặt cọc của bên mua.",
                  "3. Chất lượng: hàng mới 100%, nguyên đai kiện, sản xuất năm 2022 -2023.",
                  "4. Địa điểm giao hàng: Phòng thí nghiệm bên mua.",
                  "5. Thanh toán:",
                  "- Bằng chuyển khoản, séc theo tỷ giá bán ra của Ngân hàng Ngoại Thương tại thời điểm thanh toán (nếu là ngoại tệ).",
                  "- Thanh toán:",
                  "+ 1 lần:",
                  "  • Thanh toán 100% tổng giá trị hợp đồng trước khi giao hàng đối với hàng có sẵn.",
                  "+ 2 lần:",
                  "  • Lần 1: Thanh toán 50% tổng giá trị hợp đồng trong vòng 07 ngày ngay sau khi ký kết hợp đồng.",
                  "  • Lần 2: Thanh toán 50% tổng giá trị hợp đồng trong vòng 03 ngày kể từ ngày thông báo giao hàng và bên mua kiểm tra hàng hóa.",
                  "- Đơn vị thụ hưởng: Công ty TNHH Thiết bị Khoa học & Công nghệ Kim Ngân.",
                  "  • Số tài khoản: 186704072464536.",
                  "  • Tại: Ngân hàng TMCP phát triển TP Hồ Chí Minh, Chi nhánh Hùng Vương, Hà Nội.",
                  "6. Bảo hành 12 tháng kể từ ngày xuất kho đối với máy chính, không bảo hành phần tiêu hao và dễ vỡ.",
                  "7. Bảng báo giá có hiệu lực hết 31 tháng 12 năm 2023.",
                  "KIMTECO., LTD",
                  "Lưu Trường Thọ",
                  "Giám đốc",
                  "Mobile: 0904165623",
                  "Email: kimteco@kimteco.vn",
                ],
              },
            ],
          },
          {
            id: 3,
            images: ["/work/1.png"],
            name: "Máy khuấy Jartest (leaching test/Jar-Test) (4 vị trí độc lập)",
            description: [
              "Máy khuấy Jartest (leaching test/Jar-Test) (4 vị trí độc lập)",
              "Hãng sản xuất: Velp - Ý",
              "Model: FC4S",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Máy chính FC4S + 04 cánh khuấy + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "THÔNG TIN",
                description: [
                  "Model FC4S được thiết kế với bộ điều khiển analog với 4 vị trí độc lập.",
                  "Cùng một mẫu khách hàng có thể cài đặt lựa chọn điều kiện khác nhau.",
                  "Kết quả đáng tin cậy và lặp lại.",
                  "Động cơ khuấy DC điều khiển điện tử với tốc độ chính xác.",
                  "Tốc độ có thể cài đặt thay đổi trong khi mẫu đang chạy.",
                  "Không cài đặt được thời gian khuấy, chạy liên tục.",
                  "Số vị trí khuấy: 4 điều khiển độc lập dạng analog.",
                  "Kết cấu được làm bằng thép sơn tĩnh điện phủ lớp sơn Epoxy chịu ăn mòn hoá chất và các tác nhân cơ học thông thường.",
                  "Cánh khuấy và trục khuấy làm bằng thép không gỉ có thể điều chỉnh được độ cao.",
                  "Động cơ điều khiển DC.",
                  "Tốc độ có thể cài đặt theo các giá trị sau: 10-15-30-45-60-90-120-150-200-300 vòng/phút.",
                  "Nguồn điện sử dụng: 220V/50Hz.",
                  "Trọng lượng máy: 12.5kg.",
                  "Công suất: 18W.",
                  "Kích thước WxHxD: 645 x 347 x 260 mm.",
                  "Các phụ kiện lựa chọn thêm: Cốc thủy tinh loại 1000ml, Glass beaker 1000 ml, Phễu đong định mức bằng thủy tinh, Glass graduated imhoff cone, Giá giữ bằng gỗ phễu đong loại 2 vị trí, Stand for two imhoff cones.",
                ],
              },
              {
                name: "ĐIỀU KIỆN THƯƠNG MẠI:",
                description: [
                  "1. Giá trên là giá đã bao gồm thuế GTGT.",
                  "2. Thời gian giao hàng: 1-2 ngày đối với hàng có sẵn, và 6 ~ 8 tuần đối với hàng phải đặt, kể từ ngày bên bán nhận được tiền đặt cọc của bên mua.",
                  "3. Chất lượng: hàng mới 100%, nguyên đai kiện, sản xuất năm 2022 -2023.",
                  "4. Địa điểm giao hàng: Phòng thí nghiệm bên mua.",
                  "5. Thanh toán:",
                  "- Bằng chuyển khoản, séc theo tỷ giá bán ra của Ngân hàng Ngoại Thương tại thời điểm thanh toán (nếu là ngoại tệ).",
                  "- Thanh toán:",
                  "+ 1 lần:",
                  "  • Thanh toán 100% tổng giá trị hợp đồng trước khi giao hàng đối với hàng có sẵn.",
                  "+ 2 lần:",
                  "  • Lần 1: Thanh toán 50% tổng giá trị hợp đồng trong vòng 07 ngày ngay sau khi ký kết hợp đồng.",
                  "  • Lần 2: Thanh toán 50% tổng giá trị hợp đồng trong vòng 03 ngày kể từ ngày thông báo giao hàng và bên mua kiểm tra hàng hóa.",
                  "- Đơn vị thụ hưởng: Công ty TNHH Thiết bị Khoa học & Công nghệ Kim Ngân.",
                  "  • Số tài khoản: 186704072464536.",
                  "  • Tại: Ngân hàng TMCP phát triển TP Hồ Chí Minh, Chi nhánh Hùng Vương, Hà Nội.",
                  "6. Bảo hành 12 tháng kể từ ngày xuất kho đối với máy chính, không bảo hành phần tiêu hao và dễ vỡ.",
                  "7. Bảng báo giá có hiệu lực hết 31 tháng 12 năm 2023.",
                  "KIMTECO., LTD",
                  "Lưu Trường Thọ",
                  "Giám đốc",
                  "Mobile: 0904165623",
                  "Email: kimteco@kimteco.vn",
                ],
              },
            ],
          },
          {
            id: 4,
            images: ["/work/1.png"],
            name: "Máy khuấy Jartest (leaching test/Jar-Test) (6 vị trí điện tử hiện số)",
            description: [
              "Máy khuấy Jartest (leaching test/Jar-Test) (6 vị trí điện tử hiện số)",
              "Hãng sản xuất: Velp - Ý",
              "Model: JLT6",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Máy chính + 06 cánh khuấy + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "THÔNG TIN",
                description: [
                  "Model JLT6 được điều khiển bằng bộ vi xử lý với thiết kế đơn giản, dễ sử dụng. Bảng điều khiển phía trước dễ dàng cài đặt và quan sát các thông số cài đặt.",
                  "Cài đặt tốc độ quay từ 10 đến 300 vòng/ phút với độ phân giải là 1 vòng/ phút.",
                  "Thời gian khuấy được cài đặt trước và hiển thị thời gian hoạt động còn lại dưới dạng giờ hoặc phút.",
                  "Máy kiểm tra Jar-Test loại điện tử hiện số dùng để kiểm tra hàm lượng phèn trong nước, chọn các loại hoá chất của các chất làm đông với mục đích để di chuyển của các thành phần lơ lửng trong nước và sự ô nhiễm được xác định từ kết quả kiểm tra tại phòng thí nghiệm được gọi là phương pháp Jar-Test. Máy cũng ứng dụng kiểm tra các kim loại nặng trong nước thải bằng cách hoà tan bằng axit acetic hoặc CO2 bão hoà trong nước trước khi thải ra môi trường.",
                  "Số vị trí khuấy: 6 đồng thời.",
                  "Kết cấu được làm bằng thép sơn tĩnh điện phủ lớp sơn Epoxy chịu ăn mòn hoá chất và các tác nhân cơ học thông thường.",
                  "Cánh khuấy và trục khuấy làm bằng thép không gỉ có thể điều chỉnh được độ cao.",
                  "Động cơ điều khiển DC.",
                  "Tốc độ khuấy 10 - 300 vòng/phút, độ phân giải 1 vòng/phút.",
                  "Thời gian được điều khiển bằng bộ vi xử lý có 2 khoảng: 0-999 phút hoặc 0-99 giờ.",
                  "Nguồn điện sử dụng: 220V/50Hz.",
                  "Trọng lượng máy: 17kg.",
                  "Công suất: 19W.",
                  "Kích thước WxHxD: 935x347x260mm.",
                  "Các phụ kiện lựa chọn thêm: Cốc thủy tinh loại 1000ml, Glass beaker 1000 ml, Phễu đong định mức bằng thủy tinh, Glass graduated imhoff cone, Giá giữ bằng gỗ phễu đong loại 2 vị trí, Stand for two imhoff cones.",
                ],
              },
              {
                name: "ĐIỀU KIỆN THƯƠNG MẠI:",
                description: [
                  "1. Giá trên là giá đã bao gồm thuế GTGT.",
                  "2. Thời gian giao hàng: 1-2 ngày đối với hàng có sẵn, và 6 ~ 8 tuần đối với hàng phải đặt, kể từ ngày bên bán nhận được tiền đặt cọc của bên mua.",
                  "3. Chất lượng: hàng mới 100%, nguyên đai kiện, sản xuất năm 2022 -2023.",
                  "4. Địa điểm giao hàng: Phòng thí nghiệm bên mua.",
                  "5. Thanh toán:",
                  "- Bằng chuyển khoản, séc theo tỷ giá bán ra của Ngân hàng Ngoại Thương tại thời điểm thanh toán (nếu là ngoại tệ).",
                  "- Thanh toán:",
                  "+ 1 lần:",
                  "  • Thanh toán 100% tổng giá trị hợp đồng trước khi giao hàng đối với hàng có sẵn.",
                  "+ 2 lần:",
                  "  • Lần 1: Thanh toán 50% tổng giá trị hợp đồng trong vòng 07 ngày ngay sau khi ký kết hợp đồng.",
                  "  • Lần 2: Thanh toán 50% tổng giá trị hợp đồng trong vòng 03 ngày kể từ ngày thông báo giao hàng và bên mua kiểm tra hàng hóa.",
                  "- Đơn vị thụ hưởng: Công ty TNHH Thiết bị Khoa học & Công nghệ Kim Ngân.",
                  "  • Số tài khoản: 186704072464536.",
                  "  • Tại: Ngân hàng TMCP phát triển TP Hồ Chí Minh, Chi nhánh Hùng Vương, Hà Nội.",
                  "6. Bảo hành 12 tháng kể từ ngày xuất kho đối với máy chính, không bảo hành phần tiêu hao và dễ vỡ.",
                  "7. Bảng báo giá có hiệu lực hết 31 tháng 12 năm 2023.",
                  "KIMTECO., LTD",
                  "Lưu Trường Thọ",
                  "Giám đốc",
                  "Mobile: 0904165623",
                  "Email: kimteco@kimteco.vn",
                ],
              },
            ],
          },
          {
            id: 5,
            images: ["/work/1.png"],
            name: "Máy khuấy Jartest (leaching test/Jar-Test) (6 vị trí độc lập)",
            description: [
              "Máy khuấy Jartest (leaching test/Jar-Test) (6 vị trí độc lập)",
              "Hãng sản xuất: Velp - Ý",
              "Model: FC6S",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Máy chính FC6S + 06 cánh khuấy + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "THÔNG TIN",
                description: [
                  "Model FC6S được thiết kế với bộ điều khiển analog với 6 vị trí độc lập.",
                  "Cùng một mẫu khách hàng có thể cài đặt lựa chọn điều kiện khác nhau.",
                  "Kết quả đáng tin cậy và lặp lại.",
                  "Động cơ khuấy DC điều khiển điện tử với tốc độ chính xác.",
                  "Tốc độ có thể cài đặt thay đổi trong khi mẫu đang chạy.",
                  "Không cài đặt được thời gian khuấy, chạy liên tục.",
                  "Số vị trí khuấy: 6 điều khiển độc lập dạng analog.",
                  "Kết cấu được làm bằng thép sơn tĩnh điện phủ lớp sơn Epoxy chịu ăn mòn hoá chất và các tác nhân cơ học thông thường.",
                  "Cánh khuấy và trục khuấy làm bằng thép không gỉ có thể điều chỉnh được độ cao.",
                  "Động cơ điều khiển DC.",
                  "Tốc độ có thể cài đặt theo các giá trị sau: 10-15-30-45-60-90-120-150-200-300 vòng/phút.",
                  "Nguồn điện sử dụng: 220V/50Hz.",
                  "Trọng lượng máy: 18kg.",
                  "Công suất: 23W.",
                  "Kích thước WxHxD: 935 x 347 x 260 mm.",
                  "Các phụ kiện lựa chọn thêm: Cốc thủy tinh loại 1000ml, Glass beaker 1000 ml, Phễu đong định mức bằng thủy tinh, Glass graduated imhoff cone, Giá giữ bằng gỗ phễu đong loại 2 vị trí, Stand for two imhoff cones.",
                ],
              },
              {
                name: "ĐIỀU KIỆN THƯƠNG MẠI:",
                description: [
                  "1. Giá trên là giá đã bao gồm thuế GTGT.",
                  "2. Thời gian giao hàng: 1-2 ngày đối với hàng có sẵn, và 6 ~ 8 tuần đối với hàng phải đặt, kể từ ngày bên bán nhận được tiền đặt cọc của bên mua.",
                  "3. Chất lượng: hàng mới 100%, nguyên đai kiện, sản xuất năm 2022 -2023.",
                  "4. Địa điểm giao hàng: Phòng thí nghiệm bên mua.",
                  "5. Thanh toán:",
                  "- Bằng chuyển khoản, séc theo tỷ giá bán ra của Ngân hàng Ngoại Thương tại thời điểm thanh toán (nếu là ngoại tệ).",
                  "- Thanh toán:",
                  "+ 1 lần:",
                  "  • Thanh toán 100% tổng giá trị hợp đồng trước khi giao hàng đối với hàng có sẵn.",
                  "+ 2 lần:",
                  "  • Lần 1: Thanh toán 50% tổng giá trị hợp đồng trong vòng 07 ngày ngay sau khi ký kết hợp đồng.",
                  "  • Lần 2: Thanh toán 50% tổng giá trị hợp đồng trong vòng 03 ngày kể từ ngày thông báo giao hàng và bên mua kiểm tra hàng hóa.",
                  "- Đơn vị thụ hưởng: Công ty TNHH Thiết bị Khoa học & Công nghệ Kim Ngân.",
                  "  • Số tài khoản: 186704072464536.",
                  "  • Tại: Ngân hàng TMCP phát triển TP Hồ Chí Minh, Chi nhánh Hùng Vương, Hà Nội.",
                  "6. Bảo hành 12 tháng kể từ ngày xuất kho đối với máy chính, không bảo hành phần tiêu hao và dễ vỡ.",
                  "7. Bảng báo giá có hiệu lực hết 31 tháng 12 năm 2023.",
                  "KIMTECO., LTD",
                  "Lưu Trường Thọ",
                  "Giám đốc",
                  "Mobile: 0904165623",
                  "Email: kimteco@kimteco.vn",
                ],
              },
            ],
          },
        ],
      },
      {
        name: "Máy ly tâm",
        items: [
          {
            id: 1,
            images: ["/work/1.png", "/work/1.png", "/work/1.png"],
            name: "Máy ly tâm để bàn (6000v/phút)",
            description: [
              "Máy ly tâm để bàn (6000v/phút)",
              "Hãng sản xuất: Hermle - Đức",
              "Model: Z 206A",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính Z206A + 01 roto góc 12x 15ml mã 221.54 V01 + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Điều khiển bằng vi xử lý với màn hình hiển thị LCD.",
                  "Khoá nắp bằng điện.",
                  "Thiết kế theo các tiêu chuẩn an toàn quốc tế.",
                  "Độ ồn thấp dưới 60dBA.",
                  "Dễ dàng thay đổi roto để phù hợp với các ứng dụng phân tích.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Tốc độ tối đa: 6000 vòng/ phút.",
                  "Lực ly tâm RCF: 4427 x g.",
                  "Thể tích ly tâm tối đa: 6 x 50ml.",
                  "Cài đặt tốc độ: 200 – 6000 vòng/ phút với khoảng tăng 50 vòng/ phút.",
                  "Cài đặt thời gian: 59 phút 50 giây/ khoảng tăng 10 giây, 99 giờ 59 phút/ khoảng tăng 1 phút.",
                  "Kích thước: 28 x 26 x 37cm.",
                  "Khối lượng: 15 kg.",
                  "Công suất: 100W.",
                  "Nguồn điện: 230V / 50Hz.",
                ],
              },
            ],
          },
          {
            id: 2,
            images: ["/work/2.png", "/work/3.png"],
            name: "Máy ly tâm để bàn (6000v/phút)",
            description: [
              "Máy ly tâm để bàn (6000v/phút)",
              "Model: Z 206A",
              "Hãng sản xuất: Hermle - Đức",
              "Cung cấp bao gồm: + Máy chính Z206A + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Điều khiển bằng vi xử lý với màn hình hiển thị LCD.",
                  "Khoá nắp bằng điện.",
                  "Thiết kế theo các tiêu chuẩn an toàn quốc tế.",
                  "Độ ồn thấp dưới 60dBA.",
                  "Dễ dàng thay đổi roto để phù hợp với các ứng dụng phân tích.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Tốc độ tối đa: 6000 vòng/phút.",
                  "Lực ly tâm RCF: 4427 x g.",
                  "Thể tích ly tâm tối đa: 6 x 50ml.",
                  "Cài đặt tốc độ: 200 – 6000 vòng/phút với khoảng tăng 50 vòng/phút.",
                  "Cài đặt thời gian: 59 phút 50 giây/ khoảng tăng 10 giây; 99 giờ 59 phút/ khoảng tăng 1 phút.",
                  "Kích thước: 28 x 26 x 37cm.",
                  "Khối lượng: 15 kg.",
                  "Công suất: 100W.",
                  "Nguồn điện: 230V / 50Hz.",
                ],
              },
              {
                name: "Roto góc 12x 15ml (221.54 V01)",
                description: [
                  "Tốc độ tối đa: 6000 vòng/phút.",
                  "Lực ly tâm RCF: 4427 x g.",
                  "Bán kính tối đa: 11cm.",
                  "Góc nghiêng: 32°.",
                ],
              },
              {
                name: "Roto góc 6x 50ml (221.55 V01)",
                description: [
                  "Tốc độ tối đa: 6000 vòng/phút.",
                  "Lực ly tâm RCF: 4427 x g.",
                  "Bán kính tối đa: 11cm.",
                  "Góc nghiêng: 40°.",
                ],
              },
            ],
          },
          {
            id: 3,
            images: ["/work/1.png", "/work/1.png", "/work/1.png"],
            name: "Máy ly tâm để bàn (6000v/phút)",
            description: [
              "Máy ly tâm để bàn (6000v/phút)",
              "Model: Z 207A",
              "Hãng sản xuất: Hermle - Đức",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính Z207A + Roto góc 8x15ml + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Dòng máy ly tâm Z207A là model mới của Hermle được thiết kế cho các phòng thí nghiệm trong y tế và phòng thí nghiệm với lượng mẫu ly tâm nhỏ.",
                  "Model Z207A với roto góc loại 8x15ml với các adapter cho ly tâm ống 7, 5 hoặc 1.5ml cho ống ly tâm đáy tròn, tốc độ ly tâm tối đa 6800 v/ phút.",
                  "Bộ điều khiển vi xử lý với màn hình LCD loại rộng được trang bị chức năng “Touch-operation” giúp việc cài đặt và vận hành dễ dàng và nhanh hơn cho người sử dụng.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Khả năng ly tâm tối đa: 8 x 15 ml đáy tròn / 4 x 15 ml Falcon.",
                  "Tốc độ ly tâm tối đa: 6800 v/ phút.",
                  "Lực ly tâm đối ta: 4,445 xg (RCF).",
                  "Tốc độ ly tâm cài đặt từ: 200- 6800 v/phút.",
                  "Bộ điều khiển vi xử lý với màn hình LCD rộng.",
                  "Khóa nắp bằng điện.",
                  "Truy cập nhanh vào mẫu, tháo lắp roto dễ dàng.",
                  "Tự động ngắt khi roto mất cân bằng.",
                  "Gia tốc nhanh và giảm tốc theo 10 mức độ, không giật.",
                  "Có thể lưu được 99 chương trình ly tâm.",
                  "Có phím cài đặt nhanh cho quá trình ly tâm ngắn.",
                  "Cài đặt thời gian ly tâm từ 59 phút 50 giây (bước tăng 10 giây) hoặc 99 giờ đến 59 phút (bước tăng 1 phút).",
                  "Độ ồn: <60dBA.",
                  "Công suất: 50 W.",
                  "Nguồn điện: 100-200V/50-60Hz.",
                  "Kích thước máy WxHxD: 28x24x35mm.",
                  "Trọng lượng máy: 8kg.",
                ],
              },
              {
                name: "Adapter cho ống ly tâm",
                description: [
                  "Chèn ống cho ống ly tâm thể tích 7mm, đk 13.5mm, chiều dài max: 115mm/ chiều dài nhỏ nhất 95mm (02 chiếc/ gói) (Adapter for 7 ml tubes, Ø 13.5 mm).",
                  "Chèn ống cho ống ly tâm thể tích 7mm, đk 13.5mm, chiều dài max: 90mm/ chiều dài nhỏ nhất 62mm (02 chiếc/ gói) (Adapter for 5 ml tubes, Ø 13.5 mm).",
                  "Chèn ống cho ống ly tâm thể tích 1.5mm, đk 11mm, chiều dài ống 42mm (02 chiếc/ gói) (Adapter for 1.5ml tubes, Ø 11 mm).",
                ],
              },
            ],
          },
          {
            id: 4,
            images: ["/work/1.png", "/work/1.png", "/work/1.png"],
            name: "Máy ly tâm để bàn (6000v/phút)",
            description: [
              "Máy ly tâm để bàn (6000v/phút)",
              "Model: Z 207A",
              "Hãng sản xuất: Hermle - Đức",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính Z207A + Roto góc 4x50ml + Sách hướng dẫn sử dụng",
            ],
            price: 5000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Dòng máy ly tâm Z207A là model mới của Hermle được thiết kế cho các phòng thí nghiệm trong y tế và phòng thí nghiệm với lượng mẫu ly tâm nhỏ.",
                  "Model Z207A với roto góc loại 4x50ml với các adapter cho ly tâm ống 7, 5 hoặc 1.5ml cho ống ly tâm đáy tròn, tốc độ ly tâm tối đa 6800 v/ phút.",
                  "Bộ điều khiển vi xử lý với màn hình LCD loại rộng được trang bị chức năng “Touch-operation” giúp việc cài đặt và vận hành dễ dàng và nhanh hơn cho người sử dụng.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Khả năng ly tâm tối đa: 8 x 15 ml đáy tròn / 4 x 15 ml Falcon; 4x 50ml.",
                  "Tốc độ ly tâm tối đa: 6800 v/ phút.",
                  "Lực ly tâm đối ta: 4,445 xg (RCF).",
                  "Tốc độ ly tâm cài đặt từ: 200- 6800 v/phút.",
                  "Bộ điều khiển vi xử lý với màn hình LCD rộng.",
                  "Khóa nắp bằng điện.",
                  "Truy cập nhanh vào mẫu, tháo lắp roto dễ dàng.",
                  "Tự động ngắt khi roto mất cân bằng.",
                  "Gia tốc nhanh và giảm tốc theo 10 mức độ, không giật.",
                  "Có thể lưu được 99 chương trình ly tâm.",
                  "Có phím cài đặt nhanh cho quá trình ly tâm ngắn.",
                  "Cài đặt thời gian ly tâm từ 59 phút 50 giây (bước tăng 10 giây) hoặc 99 giờ đến 59 phút (bước tăng 1 phút).",
                  "Độ ồn: <60dBA.",
                  "Công suất: 50 W.",
                  "Nguồn điện: 100-200V/50-60Hz.",
                  "Kích thước máy WxHxD: 28x24x35mm.",
                  "Trọng lượng máy: 8kg.",
                ],
              },
            ],
          },
          {
            id: 5,
            images: ["/work/1.png", "/work/1.png", "/work/1.png"],
            name: "Máy ly tâm đa năng tốc độ tối đa 14,000 v/phút",
            description: [
              "Máy ly tâm đa năng tốc độ tối đa 14,000 v/phút",
              "Hãng sản xuất: Hermle - Đức",
              "Model: Z307",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính Z307 + Dây nguồn + Sách hướng dẫn sử dụng",
            ],
            price: 7000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Model Z307 là loại máy ly tâm nhỏ đa năng với nhiều loại phụ kiện có thể lựa chọn, bao gồm rotor cho ống microtitreplates và tốc độ cao, rotor góc cố định cho các ống ly tâm từ 15 đến 50 ml. Ngoài ra máy còn sử dụng với roto văng 4 x 100 ml được sử dụng cho các ống nuôi cấy mô và cho tất cả các ống ly tâm trong phòng xét nghiệm sinh hóa của các bệnh viện.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Tốc độ ly tâm tối đa: 14,000 vòng/phút.",
                  "Lực ly tâm tối đa (RCF): 18,624 x g.",
                  "Khoảng cài đặt tốc độ: 200-14,000 v/phút.",
                  "Thể tích ly tâm tối đa: 4 x 200ml.",
                  "Nguồn điện: 220V, 50Hz.",
                  "Kích thước: 35,5 x 33 x 47,4 cm.",
                  "Khối lượng: 30kg.",
                  "Các loại Rotor và phụ kiện lựa chọn theo các ứng dụng:",
                ],
              },
              {
                name: "Rotor góc 12 vị trí x15ml",
                description: [
                  "Roto góc 12 vị trí x15ml cho ống ly tâm đáy tròn hoặc ông đáy nhọn (falcon)",
                  "Angle rotor for 12 x 15 ml RB or Falcon tubes; Ø 17 mm.",
                  "Tốc độ ly tâm tối đa 6000 v/phút.",
                  "Lực ly tâm: 4427g.",
                  "Góc nghiêng: 32°C.",
                  "Bán kính: 11cm.",
                ],
              },
              {
                name: "Rotor góc 6 vị trí x 50ml",
                description: [
                  "Roto góc 6 vị trí x 50ml cho ống ly tâm đáy tròn hoặc ông đáy nhọn (falcon).",
                  "Angle rotor for 6 x 50 ml RB or Falcon tubes; Ø 30 mm.",
                  "Tốc độ ly tâm tối đa 6000 v/phút.",
                  "Lực ly tâm: 4427g.",
                  "Góc nghiêng: 40°C.",
                  "Bán kính: 11cm.",
                ],
              },
              {
                name: "Rotor góc 30 vị trí x15ml",
                description: [
                  "Roto góc 30 vị trí x15ml cho ống ly tâm đáy tròn hoặc ông đáy nhọn (falcon).",
                  "Angle rotor for 30 x 15 ml RB or 20 x 15 ml Falcon tubes.",
                  "Tốc độ ly tâm tối đa 4,500 v/phút.",
                  "Lực ly tâm: 4427g.",
                  "Góc nghiêng: 35°C.",
                  "Bán kính ly tâm max: 12.5/10.9cm.",
                ],
              },
              {
                name: "Rotor góc 24 vị trí x 1.5/2.0ml",
                description: [
                  "Roto góc 24 vị trí x 1.5/2.0ml cho ống ly tâm microliters.",
                  "Angle rotor for 24 x 1.5 ml (2.0 ml) tubes, hermetical sealable alu-lid.",
                  "Tốc độ ly tâm tối đa 14000v/phút.",
                  "Lực ly tâm: 18624g.",
                  "Góc nghiêng: 45°C.",
                  "Bán kính: 8.5cm.",
                ],
              },
            ],
          },
          {
            id: 6,
            images: ["/work/2.png"],
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description: [
              "Máy ly tâm lạnh ống Microlitre (ống PCR)",
              "Hãng sản xuất: Hermle – Đức",
              "Model: Z216 MK",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính model Z-216 MK (Code: 305.00 V05) + Roto góc loại 24 vị trí dùng cho ống 1.5/2.0ml có nắp đậy (Code: 220.87 V14) + Dây nguồn và sách hướng dẫn sử dụng",
            ],
            price: 9000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Được thiết kế với những tiêu chuẩn mới trong lớp học, có khả năng ly tâm đến 44 x 1,5/2,0ml cho mỗi lần chạy mẫu. Được thiết kế nhỏ gọn và hoạt động yên tĩnh phù hợp với khu vực làm việc của các phòng thí nghiệm. Hệ thống có khả năng làm lạnh mạnh mẽ, nhiệt độ lưu giữ mẫu nghiên cứu trong lúc chạy tại lực ly tâm 20.000xg là 4°C.",
                  "Không cần bảo trì bộ phận điều khiển cảm ứng.",
                  "Điều khiển bằng vi xử lý màn hình LCD lớn.",
                  "Khóa nắp bằng điện.",
                  "Cảm ứng mất cân bằng và tự tắt động cơ.",
                  "Làm lạnh bằng giá đứng.",
                  "Hệ thống làm lạnh CFC thông suốt.",
                  "Khả năng tăng tốc và giảm tốc nhanh.",
                  "Độ ồn thấp: < 60 dBA tại 21.380 xg.",
                  "Được thiết kế nhỏ gọn tiết kiệm không gian.",
                  "Quan sát mẫu nhanh với một snap trên nắp.",
                  "Được sản xuất theo tiêu chuẩn an toàn quốc tế IEC 61010.",
                  "Thao tác đơn giản.",
                  "Chương trình sử dụng dễ dàng.",
                  "Bàn phím sử dụng tương phản.",
                  "Chỉ dẫn rõ ràng về lắp ráp và những giá trị cài đặt thực.",
                  "Chọn lựa tốc độ theo lực ly tâm và lực –G với các bước tăng 10 đơn vị.",
                  "Chế độ ly tâm ngắn bằng nút Quick-key.",
                  "Có 10 mức độ tăng và giảm tốc độ khi tới chương trình vận hành.",
                  "Bộ nhớ 99 chương trình vận hành bao gồm rotor.",
                  "Khoảng nhiệt độ hoạt động: từ -20 °C đến + 40 °C.",
                  "Đặt nhiệt độ vào và hiển thị dạng °C hoặc °F.",
                  "Tuỳ chọn thời gian làm mát (Thời gian làm mát từ nhiệt độ phòng đến +4°C < 10 phút).",
                  "Thời gian ly tâm: 10 giây đến 99 giờ 59 phút hoặc liên tục (59 phút 50 giây bước tăng 10 giây, 99 giờ 59 phút bước tăng 1 phút).",
                  "Tốc độ ly tâm tối đa: 15,000 vòng/phút.",
                  "Lực ly tâm tối đa: 21,380 xg.",
                  "Thể tích ly tâm tối đa: 44 x 1,5 / 2,0 ml.",
                  "Cài đặt tốc độ ly tâm: 200 ~ 15,000 vòng/phút.",
                  "Kích thước (WxHxD): 28 x 29 x 55 cm.",
                  "Công suất: 560 W.",
                  "Khối lượng: 35 kg.",
                ],
              },
            ],
          },
          {
            id: 7,
            images: ["/work/3.png"],
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description: [
              "Máy ly tâm lạnh ống Microlitre (ống PCR)",
              "Hãng sản xuất: Hermle – Đức",
              "Model: Z216 MK",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính model Z-216 MK (Code: 305.00 V05) chưa bao gồm roto, các loại roto khách hàng lựa chọn bên dưới + Dây nguồn và sách hướng dẫn sử dụng",
            ],
            price: 9000000,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Được thiết kế với những tiêu chuẩn mới trong lớp học, có khả năng ly tâm đến 44 x 1,5/2,0ml cho mỗi lần chạy mẫu. Được thiết kế nhỏ gọn và hoạt động yên tĩnh phù hợp với khu vực làm việc của các phòng thí nghiệm. Hệ thống có khả năng làm lạnh mạnh mẽ, nhiệt độ lưu giữ mẫu nghiên cứu trong lúc chạy tại lực ly tâm 20.000xg là 4°C.",
                  "Không cần bảo trì bộ phận điều khiển cảm ứng.",
                  "Điều khiển bằng vi xử lý màn hình LCD lớn.",
                  "Khóa nắp bằng điện.",
                  "Cảm ứng mất cân bằng và tự tắt động cơ.",
                  "Làm lạnh bằng giá đứng.",
                  "Hệ thống làm lạnh CFC thông suốt.",
                  "Khả năng tăng tốc và giảm tốc nhanh.",
                  "Độ ồn thấp: < 60 dBA tại 21.380 xg.",
                  "Được thiết kế nhỏ gọn tiết kiệm không gian.",
                  "Quan sát mẫu nhanh với một snap trên nắp.",
                  "Được sản xuất theo tiêu chuẩn an toàn quốc tế IEC 61010.",
                  "Thao tác đơn giản.",
                  "Chương trình sử dụng dễ dàng.",
                  "Bàn phím sử dụng tương phản.",
                  "Chỉ dẫn rõ ràng về lắp ráp và những giá trị cài đặt thực.",
                  "Chọn lựa tốc độ theo lực ly tâm và lực –G với các bước tăng 10 đơn vị.",
                  "Chế độ ly tâm ngắn bằng nút Quick-key.",
                  "Có 10 mức độ tăng và giảm tốc độ khi tới chương trình vận hành.",
                  "Bộ nhớ 99 chương trình vận hành bao gồm rotor.",
                  "Khoảng nhiệt độ hoạt động: từ -20 °C đến + 40 °C.",
                  "Đặt nhiệt độ vào và hiển thị dạng °C hoặc °F.",
                  "Tuỳ chọn thời gian làm mát (Thời gian làm mát từ nhiệt độ phòng đến +4°C < 10 phút).",
                  "Thời gian ly tâm: 10 giây đến 99 giờ 59 phút hoặc liên tục (59 phút 50 giây bước tăng 10 giây, 99 giờ 59 phút bước tăng 1 phút).",
                  "Tốc độ ly tâm tối đa: 15,000 vòng/phút.",
                  "Lực ly tâm tối đa: 21,380 xg.",
                  "Thể tích ly tâm tối đa: 44 x 1,5 / 2,0 ml.",
                  "Cài đặt tốc độ ly tâm: 200 ~ 15,000 vòng/phút.",
                  "Kích thước (WxHxD): 28 x 29 x 55 cm.",
                  "Công suất: 560 W.",
                  "Khối lượng: 35 kg.",
                ],
              },

              {
                name: "Các loại Roto lựa chọn",
                description: [
                  "Roto góc loại 44 x 1.5/2.0ml có nắp đậy",
                  "Góc nghiêng: 32°/55°",
                  "Tốc độ ly tâm tối đa: 15,000 v/phút",
                  "Lực ly tâm tối đa: 21,127/21,379 xg",
                  "Bán kính ly tâm: 8.4/8.5cm",
                  "Đường kính ống ly tâm: 11mm",
                  "Nhiệt độ tại tốc độ max: 10°C",
                  "Roto góc loại 30 x 1.5/2.0ml có nắp đậy",
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 13,500 v/phút",
                  "Lực ly tâm tối đa: 19,151 xg",
                  "Bán kính ly tâm: 9.4cm",
                  "Đường kính ống ly tâm: 11mm",
                  "Nhiệt độ tại tốc độ max: 9°C",
                  "Roto góc loại 24 x 1.5/2.0ml có nắp đậy",
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 15,000 v/phút",
                  "Lực ly tâm tối đa: 21,379 xg",
                  "Bán kính ly tâm: 8.5cm",
                  "Đường kính ống ly tâm: 11mm",
                  "Nhiệt độ tại tốc độ max: 6°C",
                  "Roto góc loại kết hợp 24 x 1.5/2.0ml và 4x8 vị trí cho PRC stripes có nắp đậy",
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 15,000 v/phút",
                  "Lực ly tâm tối đa: cho ống micro 21,379 xg/ cho ống PCR strip 13,582 xg",
                  "Bán kính ly tâm: 8.5cm cho ống micro/ 5.4cm cho ống PCR strip",
                  "Đường kính ống ly tâm: 11mm với ống Micro; 6mm với ống PCR stripes",
                  "Nhiệt độ tại tốc độ max: 11°C",
                  "Roto góc loại 12 x 5.0ml có nắp đậy",
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 14,500 v/phút",
                  "Lực ly tâm tối đa: 19,978 xg",
                  "Bán kính ly tâm: 8.5cm",
                  "Đường kính ống ly tâm: 17mm",
                  "Nhiệt độ tại tốc độ max: 7°C",
                ],
              },
            ],
          },
          {
            id: 8,
            images: ["/work/3.png"],
            name: "Máy ly tâm lạnh ống Microlitre (ống PCR)",
            description: [
              "Máy ly tâm lạnh ống Microlitre (ống PCR)",
              "Hãng sản xuất: Hermle – Đức",
              "Model: Z207MK",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính Z207MK + Roto góc 18x1.5/2ml + Sách hướng dẫn sử dụng",
            ],
            price: 9000000,
            body: [
              {
                name: "Đặc điểm thiết kế",
                description: [
                  "Động cơ không chổi than",
                  "Bộ điều khiển vi xử lý",
                  "Tự động dừng khi mất cân bằng",
                  "Có chức năng mở khóa khẩn cấp",
                  "Buồng ly tâm bằng thép không gỉ",
                  "Hệ thống làm lạnh không CFC khoảng nhiệt độ (-20°C tới +40°C) bước tăng 1°C",
                  "Tự động nhận dạng rotor",
                  "Tháo lắp roto bằng tay không cần dụng cụ",
                  "Sản xuất theo tiêu chuẩn an toàn điện IEC 61010",
                ],
              },
              {
                name: "Chức năng bộ điều khiển",
                description: [
                  "Điều khiển bằng cảm ứng",
                  "Dễ dàng tháo tác khi mang găng tay và thao tác bằng 1 tay.",
                  "Bộ nhớ lên tới 99 chương trình",
                  "Có chức năng lựa chọn ly tâm nhanh",
                  "Có chức năng làm lạnh trước",
                  "Làm mát ổn định",
                  "Có 10 mức độ tăng và giảm tốc",
                  "Giảm tốc êm không làm vỡ mẫu",
                  "Hiển thị giá trị cài đặt và giá trị thực tế",
                  "Có thể lựa chọn tốc độ ly tâm theo v/phút hoặc lực RCF với bước tăng 10",
                  "Có chức năng cài đặt thời gian ly tâm từ 10 giây tới 99h 59 phút hoặc hoạt động liên tục.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Tốc độ tối đa: 14,500 vòng/phút.",
                  "Lực ly tâm tương đối tối đa (Max RCF): 17,157 xg.",
                  "Công suất ly tâm tối đa: 24 ống ly tâm 1.5ml/2.0ml",
                  "Khoảng tốc độ: 200-14,500 vòng/phút.",
                  "Cài đặt thời gian: + Đến 59 phút 50 giây: bước tăng 10 giây. + Đến 99 giờ 59 phút: bước tăng 1 phút.",
                  "Kích thước máy WxHxD: 28x29x55 cm.",
                  "Trọng lượng máy: 33kg.",
                  "Nguồn điện: 230V, 50-60 Hz; công suất: 320W",
                ],
              },
              {
                name: "Phụ kiện kèm theo",
                description: [
                  "Rotor góc 18 x 1.5/2.0ml",

                  "Mã số: 220.95 V08",
                  "Tốc độ tối đa: 14,500 vòng/phút",
                  "Max RCF: 17,157 xg",
                  "Công suất ly tâm tối đa: 18 ống ly tâm 1.5/2.0ml",
                  "Góc nghiêng: 45°",
                  "Bán kính ly tâm: 7.3cm",
                  "Đường kính ống ly tâm lớn nhất: 11mm",
                  "Nhiệt độ ly tâm ở tốc độ ly tâm tối đa: 0°C",

                  "Rotor góc loại 24 x 1.5/2.0ml có nắp đậy",

                  "Tốc độ tối đa: 13,000 vòng/phút",
                  "Max RCF: 16,058 xg",
                  "Công suất ly tâm tối đa: 24 ống ly tâm 1.5/2.0ml",
                  "Góc nghiêng: 45°",
                  "Bán kính ly tâm: 8.5cm",
                  "Đường kính ống ly tâm lớn nhất: 11mm",
                  "Nhiệt độ ly tâm ở tốc độ ly tâm tối đa: 0°C",
                ],
              },
            ],
          },
          {
            id: 9,
            images: ["/work/4.png"],
            name: "Máy ly tâm thường (ly tâm ống PCR)",
            description: [
              "Máy ly tâm thường (ly tâm ống PCR)",
              "Hãng sản xuất: Hermle – Đức",
              "Model: Z 216M",
              "Xuất xứ: Đức",
              "Cung cấp bao gồm: + Máy chính model Z 216 M + Roto góc loại 24 vị trí dùng cho ống 1.5/2.0ml có nắp đậy (Code: 220.87 V14) + Dây nguồn và sách hướng dẫn sử dụng",
            ],
            price: 8500000,
            body: [
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Được thiết kế với những tiêu chuẩn mới trong lớp học, có khả năng ly tâm đến 44 x 1,5/2,0ml cho mỗi lần chạy mẫu. Được thiết kế nhỏ gọn và hoạt động yên tĩnh phù hợp với khu vực làm việc của các phòng thí nghiệm.",
                  "Không cần bảo trì bộ phận điều khiển cảm ứng.",
                  "Điều khiển bằng vi xử lý màn hình LCD lớn",
                  "Khóa nắp bằng điện.",
                  "Cảm ứng mất cân bằng và tự tắt động cơ",
                  "Khả năng tăng tốc và giảm tốc nhanh",
                  "Độ ồn thấp: < 60 dBA tại 21.380 xg",
                  "Được thiết kế nhỏ gọn tiết kiệm không gian",
                  "Quan sát mẫu nhanh với một snap trên nắp",
                  "Được sản xuất theo tiêu chuẩn an toàn quốc tế IEC 61010",
                  "Thao tác đơn giản",
                  "Chương trình sử dụng dễ dàng.",
                  "Bàn phím sử dụng tương phản",
                  "Chỉ dẫn rõ ràng về lắp ráp và những giá trị cài đặt thực.",
                  "Chọn lựa tốc độ theo lực ly tâm và lực –G với các bước tăng 10 đơn vị",
                  "Chế độ ly tâm ngắn bằng nút Quick-key",
                  "Có 10 mức độ tăng và giảm tốc độ khi tới chương trình vận hành",
                  "Bộ nhớ 99 chương trình vận hành bao gồm rotor",
                  "Đặt nhiệt độ vào và hiển thị dạng oC hoặc oF.",
                  "Thời gian ly tâm: 10 giây đến 99 giờ 59 phút hoặc liên tục (59 phút 50 giây bước tăng 10 giây, 99 giờ 59 phút bước tăng 1 phút)",
                  "Tốc độ ly tâm tối đa: 15000 vòng/phút",
                  "Lực ly tâm tối đa: 21380 xg",
                  "Thể tích ly tâm tối đa: 44 x 1,5 / 2,0 ml",
                  "Cài đặt tốc độ ly tâm: 200 ~ 15000 vòng/phút",
                  "Kích thước (WxHxD): 28 x 29 x 39 cm",
                  "Công suất: 280 W",
                  "Khối lượng: 17 kg",
                ],
              },
              {
                name: "Roto góc loại 24 vị trí dùng cho ống 1.5/2.0ml có nắp đậy (Code: 220.87 V14)",
                description: [
                  "Tốc độ ly tâm tối đa: 15000 vòng/phút",
                  "Lực ly tâm tối đa: 21379 xg",
                  "Bán kính: 8,5cm",
                  "Đường kính ống: 11mm",
                  "Góc ly tâm: 45°",
                ],
              },
              {
                name: "Roto góc loại 44 x 1.5/2.0ml có nắp đậy",
                description: [
                  "Góc nghiêng: 32°/55°",
                  "Tốc độ ly tâm tối đa: 15,000 vòng/phút",
                  "Lực ly tâm tối đa: 21,127/21,379 xg",
                  "Bán kính ly tâm: 8.4/8.5cm",
                  "Đường kính ống ly tâm: 11mm",
                ],
              },
              {
                name: "Roto góc loại 30 x 1.5/2.0ml có nắp đậy",
                description: [
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 13,500 vòng/phút",
                  "Lực ly tâm tối đa: 19,151 xg",
                  "Bán kính ly tâm: 9.4cm",
                  "Đường kính ống ly tâm: 11mm",
                ],
              },
              {
                name: "Roto góc loại 24 x 1.5/2.0ml có nắp đậy",
                description: [
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 15,000 vòng/phút",
                  "Lực ly tâm tối đa: 21,379 xg",
                  "Bán kính ly tâm: 8.5cm",
                  "Đường kính ống ly tâm: 11mm",
                ],
              },
              {
                name: "Roto góc loại kết hợp 24 x 1.5/2.0ml và 4x8 vị trí cho PRC stripes có nắp đậy",
                description: [
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 15,000 vòng/phút",
                  "Lực ly tâm tối đa: cho ống micro 21,379 xg/ cho ống PCR strip 13,582 xg",
                  "Bán kính ly tâm: 8.5cm cho ống micro/ 5.4cm cho ống PCR strip",
                  "Đường kính ống ly tâm: 11mm với ống Micro; 6mm với ống PCR stripes",
                ],
              },
              {
                name: "Roto góc loại 12 x 5.0ml có nắp đậy",
                description: [
                  "Góc nghiêng: 45°",
                  "Tốc độ ly tâm tối đa: 14,500 vòng/phút",
                  "Lực ly tâm tối đa: 19,978 xg",
                  "Bán kính ly tâm: 8.5cm",
                  "Đường kính ống ly tâm: 17mm",
                ],
              },
            ],
          },
          {
            id: 10,
            images: ["/work/1.png"],
            name: "Máy ly tâm ống Microlitre (ống PCR)",
            model: "Z207M",
            manufacturer: "Hermle - Đức",
            origin: "Đức",
            includes: [
              "Máy chính Z207M",
              "Roto góc 24x1.5/2ml",
              "Sách hướng dẫn sử dụng",
            ],
            description: [
              "Đặc điểm thiết kế:",
              "- Bộ vi xử lý với màn hình hiển thị LCD rộng.",
              "- Khóa nắp liên động bằng điện.",
              "- Tự phát hiện chế độ không cân bằng và tự động ngắt.",
              "- Hệ thống làm mát bằng không khí.",
              "- Tăng và giảm tốc nhanh trong vòng 13 giây.",
              "- Độ ồn <60dBA khi ở tốc độ tối đa.",
              "- Dễ dàng tháo rời rotor mà không cần dụng cụ.",
              "- Sản xuất theo tiêu chuẩn an toàn quốc tế IEC 61010",
            ],
            controller: [
              "Bộ điều khiển và hiển thị:",
              "- Bảng điều khiển với phím chạm.",
              "- Dễ dàng tháo tác khi mang găng tay và thao tác bằng 1 tay.",
              "- Hiển thị đồng thời giá trị cài đặt và giá trị thực.",
              "- Lựa chọn tốc độ theo vòng/phút hoặc g-force, bước tăng là 10.",
              "- Có 10 tốc độ tăng và giảm tốc.",
              "- Cài đặt thời gian ly tâm: từ 10 giây đến 99 giờ 59 phút hoặc ly tâm liên tục.",
              "- Cho phép lưu được 99 chương trình ly tâm.",
              "- Phím bấm nhanh cho các lần ly tâm ngắn.",
            ],
            technical_specs: {
              max_speed: "13500 vòng/phút",
              max_rcf: "17317 xg",
              max_capacity: "24 ống ly tâm 1.5ml/2.0ml",
              speed_range: "200- 13500 vòng/phút",
              time_setting: [
                "Đến 59 phút 50 giây: bước tăng 10 giây.",
                "Đến 99 giờ 59 phút: bước tăng 1 phút.",
              ],
              dimensions: "28x24x35 cm",
              weight: "12.5 kg",
              power: "230V, 50-60 Hz; công suất: 170W",
            },
            accessories: [
              {
                name: "Rotor góc 24 x 1.5/2.0ml",
                code: "221.59 V02",
                max_speed: "13500 vòng/phút",
                max_rcf: "17317 xg",
                max_capacity: "24 ống ly tâm 1.5/2.0ml",
                angle: "45°",
                radius: "8.5 cm",
                tube_diameter: "11 mm",
              },
            ],
            price: 328000,
          },
        ],
      },
      {
        name: "Kính hiển vi",
        items: [
          {
            id: 1,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Kính hiển vi 3 mắt",
            description: [
              "Kính hiển vi 3 mắt",
              "Hãng sản xuất: Optika - Ý",
              "Model: B-193PL",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Máy chính + Túi phủ chống bụi + Dầu soi 10ml + Hướng dẫn sử dụng (bản tải trên website)",
            ],
            price: 0,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Chế độ quan sát: nền sáng.",
                  "Thân máy bằng nhôm đúc.",
                  "Đầu quan sát loại 3 mắt (tỷ lệ chia 50/50) góc nghiêng 30°, có thể xoay tròn 360°, khoảng cách giữa 2 mắt 48 ~ 75mm, có điều chỉnh diop trên mắt trái.",
                  "Thị kính trường quan sát 18mm, độ hong đại 10x.",
                  "Mâm vật kính 4 vị trí, quay được theo hai hướng trên ổ bi.",
                  "Vật kính: loại N-PAN, được xử lý chống mốc, khoảng cách tiêu điểm 45mm, độ hong đại 40x ~ 1000x.",
                  "Bàn soi mẫu loại 2 lớp, kích thước 125 x 115mm. Cơ cấu chuyển động giá đỡ và bánh răng, khoảng di chuyển 70x30mm, độ chính xác 0.1mm.",
                  "Bộ tụ quang: Abbe 1.25 N.A.",
                  "Bộ lấy nét có thể điều chỉnh thô và tinh. Khoảng thô 18mm, phân giải 0.4mm. Khoảng tinh 100 bước, phân giải 4µm.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Nguồn sáng: X-LED2 3W, có điều chỉnh cường độ sáng, tuổi thọ đèn > 65.000 giờ, nhiệt độ mầu 6300K, công suất tối đa 6W.",
                  "Nguồn điện: đầu vào 100/240VAC, 50/60Hz. Đầu ra 6VDC 2.5A.",
                  "Kích thước: 440 (cao) x 235 (rộng) x 320 (sâu) mm.",
                  "Khối lượng: 6.5kg.",
                ],
              },
            ],
          },
          {
            id: 2,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Kính hiển vi 3 mắt (Kết nối với camera)",
            description: [
              "Kính hiển vi 3 mắt (Kết nối với camera)",
              "Hãng sản xuất: Optika – Ý",
              "Model: B-293",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Thân kính: 1 chiếc + Thị kính (mắt): 02 chiếc 10x/20mm + Bộ thị kính: N-PLAN 4x/0.10, N-PLAN 10x/0.25, N-PLAN 40x/0.65, N-PLAN 100x/1.25 (Oil/Water) (sử dụng dầu soi) + Bàn xa kẹp mẫu :1 chiếc + Bóng đèn X-LED: 1 chiếc + Mâm lắp vật kính: 1 chiếc loại 4 vị trí + Đầu lắp thị kính: 1 bộ + Túi che kính: 1 chiếc + Lọ dầu soi: 01 lọ + Sách hướng dẫn sử dụng",
            ],
            price: 0,
            body: [
              {
                name: "Đặc điểm nổi bật",
                description: [
                  "Kính hiển bi được sử dụng rộng rãi trong lĩnh vực giáo dục và phòng thí nghiệm. Thiết kế tinh tế, gọn nhẹ và có tính ổn định cao, chế độ quan sát dạng ánh sáng truyền qua.",
                  "Độ phóng đại tối đa 1000 lần.",
                  "Đầu quan sát: 03 mắt.",
                  "Nguồn sáng: nguồn sáng loại đèn X-LED ánh sáng trắng, có núm điều khiển cường độ ánh sáng được đặt phái bên trái của kính, công suất đèn 3.6W, tương đương với bóng đèn Halogen 50W, tuổi thọ trung bình là 50,000h.",
                  "Chế độ quan sát: nền sáng.",
                  "Tiêu cự: dạng đồng trục (độ chia 0.002mm) với giới hạn trên, ngăn chặn tiếp xúc giữa vật kính và mẫu vật, điều chỉnh tiêu cự dạng đồng trục.",
                  "Bàn soi mẫu: dạng bàn kép trượt trên nhau, kích thước 150x 139mm, di chuyển theo X-Y khoảng dịch chuyển 70x 30, giá giữ cho slide, đai kẹp dạng X, thước trên cả 2 trục, độ chính xác 0.1mm.",
                  "Đầu lắp vật kính: 4 vị trí lắp vật kính được luân chuyển trên vòng xoay.",
                ],
              },
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Kích thước: H370 mm x W235 mm x D290 mm.",
                  "Khối lượng: 6.5 kg.",
                ],
              },
            ],
          },
          {
            id: 3,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Kính hiển vi sinh học 3 mắt (Kính kết nối với camera)",
            description: [
              "Kính hiển vi sinh học 3 mắt (Kính kết nối với camera)",
              "Model: B-293Pli",
              "Hãng sản xuất: Optika- Ý",
              "Xuất xứ: Ý",
              "Cấu hình cung cấp: + Thân kính: 1 chiếc + Thị kính (mắt): 02 chiếc 10x/20mm + IOS 4X, N.A. 0,10, W.D. 18 mm + IOS 10X, N.A. 0,25, W.D. 7 mm + IOS 40X, N.A. 0,65, W.D. 0,53 mm + IOS 100X, N.A. 1,25, W.D. 0,13 mm (sử dụng dầu soi) + Bàn xa kẹp mẫu :1 chiếc + Bóng đèn X-LED: 1 chiếc + Mâm lắp vật kính: 1 chiếc loại 4 vị trí + Đầu lắp thị kính: 1 bộ + Túi che kính: 1 chiếc + Lọ dầu soi: 01 lọ + Sách hướng dẫn sử dụng",
            ],
            price: 0,
            body: [
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Nguồn sáng loại X-LED với đèn LED ánh sáng trắng, điều khiển cường độ sáng bởi một núm xoay bên trái thân kính.",
                  "Đèn LED công suất 3.6W, cho cường độ sáng tương ứng với bóng đèn halogen 30-35W.",
                  "Nhiệt độ màu: 6300K.",
                  "Tuổi thọ trung bình của đèn LED là 50000 giờ.",
                  "Nguồn điện sử dụng: 100/240Vac, 50/60Hz, đầu ra: 6Vdc 1A.",
                  "Công suất max.: 7W.",
                  "Chế độ quan sát: Nền sáng (Brightfield).",
                  "Điều chỉnh tiêu cự: Điều chỉnh thô và chỉnh tinh đồng trục (độ chia, 0.002mm) với cơ cấu giới hạn phía trên, tránh vật kính va chạm vào mẫu. Có khả năng điều chỉnh độ căng của núm vặn.",
                  "Bàn soi mẫu: Bàn đặt mẫu hai lớp với hệ thống dịch chuyển cơ, kích thước 150x133mm, khoảng dịch chuyển theo chiều X-Y là 75x50mm, hệ thống kẹp tiêu bản sử dụng cho một tiêu bản. Dẫn động bằng dây đai cho dịch chuyển theo chiều X. Có thang chia trên các trục X-Y, độ chia 0,1 mm.",
                  "Đầu lắp vật kính: Có 4 vị trí lắp vật kính, xoay tròn với hệ thống bi định vị vị trí vật kính.",
                  "Đầu quan sát: Loại 2 mắt, nghiêng 30° và có thể quay 360°. Điều chỉnh bù đi ốp trên mắt trái. Khoảng cách liên đồng tử có thể điều chỉnh trong khoảng 48-75 mm.",
                  "Thị kính: Thị kính thị trường rộng WF10X/20 với thị trường 20mm.",
                  "Các vật kính: Các vật kính E-Plan hiệu chuẩn vô cực (IOS) tiêu sắc.",
                  "Tất cả các vật kính đã được xử lý chống nấm mốc.",
                  "Bộ tụ sáng: Loại tụ quang Abbe condenser, A.N. 1,25 với hệ thống định tâm, điều chỉnh độ cao thấp.",
                  "Kích thước (HxWxD): 370x235x290 mm.",
                ],
              },
            ],
          },
          {
            id: 4,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Camera cho kính hiển vi",
            description: [
              "Camera cho kính hiển vi",
              "Hãng sản xuất: Optika – Ý",
              "Model: C-B1",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Cáp USB 1.8m + Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm + Tiêu bản chuẩn + C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli + Phần mềm kết nối với máy tính download trực tiếp trên website",
            ],
            price: 0,
            body: [
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Độ phân giải: 1.3 MP (1280x1024).",
                  "Cổng kết nối USB 2.0.",
                  "Cảm biến hình ảnh: APTINA CMOS.",
                  "Định dạng ảnh: 5/4.",
                  "Kích thước điểm ảnh: 3.6x3.6 µm.",
                  "Tốc độ khung hình với độ phân giải tối đa: 15@1280x1024.",
                  "Tốc độ khung hình với độ phân giải khác: 50@320x256.",
                  "Độ nhạy: 1 V/lux-second.",
                  "Tỷ số tín hiệu/nhiễu: 44 DB.",
                  "Dải tần nhạy sáng: 74 DB.",
                  "Chuyển đổi ADC: 8 Bit.",
                  "Độ sâu mầu: 1, 4, 8, 24 Bit.",
                  "Thời gian phơi sáng: 0.14 msec - 2 sec.",
                  "Binning 1x1; 2x2; 3x3.",
                  "Khoảng lọc IR: 380-650 nm.",
                  "Nguồn điện: PC USB.",
                  "Kích thước: 58 x 58 x 36.4 mm.",
                  "Khối lượng: 0.18 kg.",
                  "Phần mềm: PROVIEW hoặc LITEVIEW, chạy trên hệ điều hình Windows 7/8/10 (32bit)/10 (64bit), Osx (MAC Osx) và Linux.",
                  "Yêu cầu cấu hình PC: Intel Core2 - 2.8GZ và RAM 2GB.",
                ],
              },
            ],
          },
          {
            id: 5,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Bộ Camera",
            description: [
              "Model: C-B5",
              "Hãng sản xuất: Optika – Ý",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Cáp USB 1.8m + Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm + Tiêu bản chuẩn + C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli + Phần mềm kết nối với máy tính download trực tiếp trên website",
            ],
            price: 0,
            body: [
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Độ phân giải: 5.1 MP (2592 x 1944).",
                  "Cổng ra: USB 2.0.",
                  "Cảm biến: 1/2.5’’.",
                  "Công nghệ cảm biến CMOS.",
                  "Khung ảnh: 4/3.",
                  "Kích thước Pixel: 2.2 x 2.2 μm.",
                  "Độ phẩn giải tốc độ khung hình: 27 fps (1280x 960); 90fps (640x 480).",
                  "Bộ lọc: 380-650 nm (IR-cut filter).",
                  "Độ nhậy: 0.31V/lux- second.",
                  "Mầu: 1 Bit; 4 Bit; 8 Bit; 24 Bit.",
                  "Nguồn Camera: PC USB.",
                  "Phần mềm: PROVIEW hoặc LITEVIEW chạy trên: Win XP / Win Vista / Win 7 / Win 8 / Win 10 (32 o 64 bit) OSx (Mac OSx) Linux.",
                  "Yêu cầu máy tính tối thiểu: CPU: Equal to Intel Core2 2.8GHz or higher RAM: 2 GB or more USB port: USB 2.0, at least two ports.",
                ],
              },
            ],
          },
          {
            id: 6,
            images: [
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
              "/work/Kính hiển vi.png",
            ],
            name: "Bộ Camera",
            description: [
              "Model: C-B10+",
              "Hãng sản xuất: Optika – Ý",
              "Xuất xứ: Ý",
              "Cung cấp bao gồm: + Cáp USB 1.8m + Adapter camera 0.37X cho thị kính 23mm, 30 hoặc 30.5mm + Tiêu bản chuẩn + C mount adapter kết nối giữa camera và kính B-293, P-193, B-293Pli + Phần mềm kết nối với máy tính download trực tiếp trên website",
            ],
            price: 0,
            body: [
              {
                name: "Thông số kỹ thuật",
                description: [
                  "Độ phân giải: 10 MP (3584 x 2748).",
                  "Cổng ra: USB 3.0.",
                  "Cảm biến: 1/2.3’’.",
                  "Công nghệ cảm biến CMOS.",
                  "Khung ảnh: 4/3.",
                  "Kích thước Pixel: 1.67 x 1.67 µm.",
                  "Độ phẩn giải tốc độ khung hình: 38 fps (896 x 684).",
                  "Bộ lọc: 380-650 nm (IR-cut filter).",
                  "Độ nhậy: 0.31V/lux- second.",
                  "Mầu: 1 Bit; 4 Bit; 8 Bit; 24 Bit.",
                  "Nguồn Camera: PC USB.",
                  "Phần mềm: PROVIEW hoặc LITEVIEW chạy trên: Win XP / Win Vista / Win 7 / Win 8 / Win 10 (32 o 64 bit) OSx (Mac OSx) Linux.",
                  "Yêu cầu máy tính tối thiểu: CPU: Equal to Intel Core2 2.8GHz or higher RAM: 2 GB or more USB port: USB 2.0, at least two ports.",
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
